#!/bin/bash

TEMP1=${TMP:-"/tmp"}/output_in$$
TEMP2=${TMP:-"/tmp"}/output_out$$

PARSER="$(berkeley_parser_location)"

MODEL=$1

if test "$2"; then
  NUMBER=$2
else
  NUMBER=1
fi

sed 's/^EOS.*//' > ${TEMP1}

java -server -mx800m -jar ${PARSER} -keepFunctionLabels -gr ${MODEL} -useGoldPOS -maxLength 400 -kbest ${NUMBER} -inputFile ${TEMP1} -outputFile ${TEMP2}

cat ${TEMP2} | \
sed 's/^( /(TOP /; s/ )$/)/' | \
awk -v SIZE=${NUMBER} '

BEGIN {
 if (SIZE > 1) { printf ("(number %s)\n", SIZE) }
}

NF == 0 {
  for (i = pointer; i < SIZE; i++) {
    print store
  }
  pointer=0
  next
}

{
  pointer++
  store = $0
  print store

}

'

rm ${TEMP1} ${TEMP2}

