#!/bin/bash

PATH=$(dirname $0)/../bin:$PATH

####################
# help information #
####################

function help_information () {

cat 1>&2 << END
NAME
      tsurgeon_script - pipeline tsurgeon

SYNOPSIS
      tsurgeon_script script

DESCRIPTION
      This wrapper script runs stanford-tregex.jar in the tsurgeon mode
      as a filter changing stdin.  At least one tsurgeon script must be
      supplied.

      Before tsurgeon gets to see any script content, the script content
      is passed through the m4 macro processor.

      A tsurgeon script is a file containing a list of pattern and
      transformation operation list pairs.  That is, it is a sequence of
      pairs of a Tregex pattern on one or more lines, then a blank line
      (empty or whitespace), then a list of transformation operations
      one per line to apply when the pattern is matched, and then
      another blank line (empty or whitespace).  Note the need for blank
      lines: The code crashes if they are not present as separators.

      The character % introduces a comment that extends to the end of the
      line.  All other intended uses of % must be escaped as \% .

      Also lines that begin .R and end .E are commented out. It is not
      necessary to close .R, in which case all lines are commented out
      from the instance of .R to the end of the given script.

OPTIONS
END

cat $0 | grep " \# " 1>&2
}

while test $# -gt 0 ; do
  case "$1" in

      --debug)   # see modified script
         DEBUG=1 ; shift ;;

      -*)        # show this help message
         help_information
         exit ;;

      *)         # filename to source the tsurgeon script content
         SCRIPT="${SCRIPT} $1" ; shift ;;
 
  esac
done


######################
# script starts here #
######################

INPUT=${TMP:-"/tmp"}/output_in$$
MODIFIED_SCRIPT=${TMP:-"/tmp"}/output_ms$$

# collect and comment script content
cat ${SCRIPT} | m4 | awk '
$1 ~ /^\.R/ { remove_all++ ; next }

$1 ~ /^\.E/ { remove_all-- ; next }

remove_all != 0	{ next }

{ print }
' > "${MODIFIED_SCRIPT}"

# collect input
cat > "${INPUT}"

# show modified tsurgeon script
if test "${DEBUG}"; then
  cat "${MODIFIED_SCRIPT}"
# ensure input has content
elif test $(cat "${INPUT}" | wc -l) -gt 0; then
  # simple cat when there are no script commands
  if test $(cat "${MODIFIED_SCRIPT}" | wc -l) -eq 0; then
    cat "${INPUT}"
  else
    # establish location of stanford-tregex.jar
    TREGEX="$(tregex_location)"
    # run tsurgeon
    java -mx300m -cp "${TREGEX}" edu.stanford.nlp.trees.tregex.tsurgeon.Tsurgeon -treeFile "${INPUT}" "${MODIFIED_SCRIPT}" -s
  fi
fi

rm -f "${MODIFIED_SCRIPT}" "${INPUT}"

